/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package x20170913;

import java.awt.Font;
import javax.swing.JOptionPane;

/**
 *
 * @author Dani
 */
public class KonyaDaniel_SzemszamGui extends javax.swing.JFrame {

    /**
     * Creates new form SzemelyiEllenorzoGUI
     */
    public KonyaDaniel_SzemszamGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbSzemSzam = new javax.swing.JLabel();
        tfSzemSzam = new javax.swing.JTextField();
        btnEllenoriz = new javax.swing.JButton();
        lbCim = new javax.swing.JLabel();
        lbEredmeny = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Bevitel"));

        lbSzemSzam.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbSzemSzam.setText("Személyi szám:");

        btnEllenoriz.setText("ELLENŐRZÉS");
        btnEllenoriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEllenorizActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbSzemSzam, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfSzemSzam, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEllenoriz, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSzemSzam, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSzemSzam, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEllenoriz, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        lbCim.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lbCim.setText("Személyi szám ellenőrző");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbEredmeny, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(lbCim))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbCim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbEredmeny, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEllenorizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEllenorizActionPerformed
        String szemSzam = tfSzemSzam.getText();
        int szulEv;
        
        lbEredmeny.setFont(new Font("Dialog", Font.PLAIN, 18));

        if (szemSzam.length() > 11 || szemSzam.length() < 11) {
            JOptionPane.showMessageDialog(rootPane, "Kérem, csak 11 szám hosszúságú személyi számot adjon meg!", "Hosszúsági hiba", JOptionPane.ERROR_MESSAGE);
        } else {
            try{
            szulEv = Integer.parseInt(szemSzam.substring(1, 3));

            if (szulEv < 97) {
                RegiAlgoritmus(szemSzam);
            } else {
                UjAlgoritmus(szemSzam);
            }
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(rootPane, "Kérem, csak számokat adjon meg!", "Formai hiba", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEllenorizActionPerformed

    void RegiAlgoritmus(String szemSzam) {
        int ellenorzendoSzam = Integer.parseInt(szemSzam.substring(szemSzam.length() - 1));
        int ellenorzoSzam = 0;
        int nem = Integer.parseInt(szemSzam.substring(0, 1));
        int k;
        
        for (int i = 0; i < szemSzam.length(); i++) {

            k = Integer.parseInt(szemSzam.substring(i, i + 1));

            ellenorzoSzam += k * (i + 1);
        }

        if (ellenorzoSzam % 11 != ellenorzendoSzam) {
            lbEredmeny.setText("<html><font style='color:#DC3545'>A megadott személyi szám érvénytelen!</font></html>");
        } else {
            lbEredmeny.setText("<html>A megadott személyi szám alapján a személy neme: " + (nem % 2 == 0 ? "<font style='color:#F82EF6'>Nő</font>" : "<font style='color:#3A8EE8'>Férfi</font>") + "<br> <font style='color:#5CB85C'>Érvényes!</font></html>");
        }
    }

    void UjAlgoritmus(String szemSzam) {
        int ellenorzendoSzam = Integer.parseInt(szemSzam.substring(szemSzam.length() - 1));
        int ellenorzoSzam = 0;
        int nem = Integer.parseInt(szemSzam.substring(0, 1));
        int k;
        int j = 0;

        for (int i = szemSzam.length() - 1; i >= 0; i--) {

            k = Integer.parseInt(szemSzam.substring(j, j + 1));

            ellenorzoSzam += k * i;

            j++;
        }

        if (ellenorzoSzam % 11 != ellenorzendoSzam) {
            lbEredmeny.setText("<html><font style='color:#DC3545'>A megadott személyi szám érvénytelen!</font></html>");
        } else {
            lbEredmeny.setText("<html>A megadott személyi szám alapján a személy neme: " + (nem % 2 == 0 ? "<font style='color:#F82EF6'>Nő</font>" : "<font style='color:#3A8EE8'>Férfi</font>") + "<br> <font style='color:#5CB85C'>Érvényes!</font></html>");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonyaDaniel_SzemszamGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonyaDaniel_SzemszamGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonyaDaniel_SzemszamGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonyaDaniel_SzemszamGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonyaDaniel_SzemszamGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEllenoriz;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbCim;
    private javax.swing.JLabel lbEredmeny;
    private javax.swing.JLabel lbSzemSzam;
    private javax.swing.JTextField tfSzemSzam;
    // End of variables declaration//GEN-END:variables
}
