/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package x20170920;

import x20170913.SzemelyiSzam;
import java.awt.Font;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Dani
 */
public class KonyaDaniel_SzemSzamGeneratorGUI extends javax.swing.JFrame {

    /**
     * Creates new form SzemSzamGeneratorGUI
     */
    public KonyaDaniel_SzemSzamGeneratorGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbSzemSzam = new javax.swing.JLabel();
        lbGen = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        genList = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        tfSzemSzamGen = new javax.swing.JTextField();
        btnGen = new javax.swing.JButton();
        lbHany = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tfSzemSzamEll = new javax.swing.JTextField();
        lbSzemSzamEll = new javax.swing.JLabel();
        btnEllenorzes = new javax.swing.JButton();
        lbEredmeny = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbSzemSzam.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lbSzemSzam.setText("Személyi szám generáló és ellenőrző");

        lbGen.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbGen.setText("Generált személyi számok");

        genList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                genListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(genList);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Generálás"));

        btnGen.setText("Generálás");
        btnGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenActionPerformed(evt);
            }
        });

        lbHany.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbHany.setText("Hány személyi szám");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbHany)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfSzemSzamGen, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGen)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSzemSzamGen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbHany)
                    .addComponent(btnGen))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ellenőrzés"));

        lbSzemSzamEll.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbSzemSzamEll.setText("Személyi szám");

        btnEllenorzes.setText("Ellenőrzés");
        btnEllenorzes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEllenorzesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbSzemSzamEll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfSzemSzamEll, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEllenorzes)
                        .addGap(0, 71, Short.MAX_VALUE))
                    .addComponent(lbEredmeny, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSzemSzamEll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSzemSzamEll)
                    .addComponent(btnEllenorzes))
                .addGap(18, 18, 18)
                .addComponent(lbEredmeny, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(99, 99, 99))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(lbSzemSzam, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbGen)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbGen, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbSzemSzam, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(41, 41, 41))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenActionPerformed
        SzemelyiSzam szemelyiSzam = new SzemelyiSzam();
        genList.setModel(listModel);
        listModel.removeAllElements();
        String strSzemSzam;
        
        
        File file = letrehozFajl();
        
        for (int i = 0; i < Integer.parseInt(tfSzemSzamGen.getText()); i++) {
            strSzemSzam = szemelyiSzam.generalSzemSzam();
            listModel.addElement(strSzemSzam);
            fajlbaKiir(strSzemSzam,file);
        }
        
        System.out.println(listModel.size());
    }//GEN-LAST:event_btnGenActionPerformed

    private void genListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genListMouseClicked
        String aktSzemSzam = genList.getSelectedValue();

        tfSzemSzamEll.setText(aktSzemSzam);
    }//GEN-LAST:event_genListMouseClicked

    private void btnEllenorzesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEllenorzesMouseClicked
        String szemSzam = tfSzemSzamEll.getText();
        int szulEv;

        lbEredmeny.setFont(new Font("Dialog", Font.PLAIN, 18));

        if (szemSzam.length() > 11 || szemSzam.length() < 11) {
            JOptionPane.showMessageDialog(rootPane, "Kérem, csak 11 szám hosszúságú személyi számot adjon meg!", "Hosszúsági hiba", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                szulEv = Integer.parseInt(szemSzam.substring(1, 3));

                if (szulEv < 97) {
                    RegiAlgoritmus(szemSzam);
                } else {
                    UjAlgoritmus(szemSzam);
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "Kérem, csak számokat adjon meg!", "Formai hiba", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEllenorzesMouseClicked

    void fajlbaKiir(String szemszam, File file) {
        PrintWriter pw = null;
        try {
            pw = new PrintWriter(new FileOutputStream(file, true));
            pw.println(szemszam);
            
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        } finally {
            pw.close();
        }
    }

    void RegiAlgoritmus(String szemSzam) {
        int ellenorzendoSzam = Integer.parseInt(szemSzam.substring(szemSzam.length() - 1));
        int ellenorzoSzam = 0;
        int nem = Integer.parseInt(szemSzam.substring(0, 1));

        for (int i = 0; i < szemSzam.length(); i++) {

            int k = Integer.parseInt(szemSzam.substring(i, i + 1));

            ellenorzoSzam += k * (i + 1);
        }

        if (ellenorzoSzam % 11 != ellenorzendoSzam) {
            lbEredmeny.setText("<html><font style='color:#DC3545'>A megadott személyi szám érvénytelen!</font></html>");
        } else {
            lbEredmeny.setText("<html>A megadott személyi szám alapján a személy neme: " + (nem % 2 == 0 ? "<font style='color:#F82EF6'>Nő</font>" : "<font style='color:#3A8EE8'>Férfi</font>") + "<br> <font style='color:#5CB85C'>Érvényes!</font></html>");
        }
    }

    void UjAlgoritmus(String szemSzam) {
        int ellenorzendoSzam = Integer.parseInt(szemSzam.substring(szemSzam.length() - 1));
        int ellenorzoSzam = 0;
        int nem = Integer.parseInt(szemSzam.substring(0, 1));

        int j = 0;

        for (int i = szemSzam.length() - 1; i >= 0; i--) {

            int k = Integer.parseInt(szemSzam.substring(j, j + 1));

            ellenorzoSzam += k * i;

            j++;
        }

        if (ellenorzoSzam % 11 != ellenorzendoSzam) {
            lbEredmeny.setText("<html><font style='color:#DC3545'>A megadott személyi szám érvénytelen!</font></html>");
        } else {
            lbEredmeny.setText("<html>A megadott személyi szám alapján a személy neme: " + (nem % 2 == 0 ? "<font style='color:#F82EF6'>Nő</font>" : "<font style='color:#3A8EE8'>Férfi</font>") + "<br> <font style='color:#5CB85C'>Érvényes!</font></html>");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonyaDaniel_SzemSzamGeneratorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonyaDaniel_SzemSzamGeneratorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonyaDaniel_SzemSzamGeneratorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonyaDaniel_SzemSzamGeneratorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonyaDaniel_SzemSzamGeneratorGUI().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEllenorzes;
    private javax.swing.JButton btnGen;
    private javax.swing.JList<String> genList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbEredmeny;
    private javax.swing.JLabel lbGen;
    private javax.swing.JLabel lbHany;
    private javax.swing.JLabel lbSzemSzam;
    private javax.swing.JLabel lbSzemSzamEll;
    private javax.swing.JTextField tfSzemSzamEll;
    private javax.swing.JTextField tfSzemSzamGen;
    // End of variables declaration//GEN-END:variables
    
    private DefaultListModel listModel = new DefaultListModel();

    private File letrehozFajl() {
        String eleresiUt = System.getProperty("user.home") + "/Documents/generalt/";
        File file = new File(eleresiUt+"generalt.txt");
        try {
            if (file.exists()) {
                file = new File(eleresiUt);
                for (File fileok : file.listFiles()) {
                    fileok.delete();
                }
                file.delete();
                file = new File(eleresiUt);
                file.mkdirs();
                file = new File(eleresiUt + "generalt.txt");
                file.createNewFile();
            } else {
                file = new File(eleresiUt);
                file.mkdirs();
                file = new File(eleresiUt + "generalt.txt");
                file.createNewFile();
            }
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        return file;
    }
}
